routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('welcome');
});

Auth::routes();

Route::resources([
    'club' => 'ClubController',
    'clubadmin' => 'ClubAdminController',
    'group' => 'GroupController',
    'team' => 'TeamController',
    'player' => 'PlayerController'
]);

Route::get('/home', 'HomeController@index')->name('home');
Route::get('/private', 'HomeController@superadmin')->name('superadmin');
Route::get('logout', 'Auth\LoginController@logout')->name('logout');

Route::post('check-player', 'PlayerController@checkPlayer')->name('checkPlayer');

Route::impersonate();

app/Club.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Club extends Model
{
   
}

app/Http/Controllers/ClubController.php
<?php

namespace App\Http\Controllers;

use App\Club;
use App\Player;
use App\PlayerGroup;
use App\Team;
use App\User;
use Illuminate\Http\Request;

class ClubController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $clubList = Club::all();

        $description = "Request For Club List ";

        activity()->log($description);


        return view('club.club_list',compact('clubList'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        return view('club.add_club');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $request->validate([
            'name' => 'required'
        ]);

        $club = new Club;
        $club->name = $request->name;
        $club->save();

        $description = "New Club '".$request->name."' added";

        activity()->log($description);
        
        return redirect(route('club.index'))->with('messages', [
              [
                  'type' => 'success',
                  'title' => 'Club',
                  'message' => 'Club Successfully added.',
              ],
        ]); 
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {

    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        $getClubInfo = Club::find($id);

        $description = "Edit Request for club '".$groupInfo->name."'";

        activity()->log($description);

        return view('club.edit_club',compact('getClubInfo'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        $request->validate([
            'name' => 'required'
        ]);

        $club = Club::findOrFail($id);
        $club->name = $request->name;
        $club->save();

        $description = "Club Updated ".$request->name;

        activity()->log($description);
        
        return redirect(route('club.index'))->with('messages', [
              [
                  'type' => 'success',
                  'title' => 'Club',
                  'message' => 'Club Successfully updated.',
              ],
        ]); 
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        $club = Club::where('id',$id)->delete();

        $deleteUser = User::where('club_id',$id)->delete();
        $team = Team::where('id',$id)->pluck('id');
        $group = PlayerGroup::whereIn('team_id',$team)->pluck('id');
        $deltePlayer = Player::whereIn('group_id',$group)->delete();
        $deletegroup = PlayerGroup::whereIn('team_id',$team)->delete();
        $deleteteam = Team::where('id',$id)->delete();

        $description = "Club #".$id." deleted";

        activity()->log($description);

        return redirect(route('club.index'))->with('messages', [
              [
                  'type' => 'success',
                  'title' => 'Club',
                  'message' => 'Club Successfully deleted.',
              ],
        ]); 
    }
}

resources/views/club/add_club.blade.php
@extends('layouts.admin')
@section('title','Add Club')
@section('content')
<div id="content" class="content">
	<!-- begin breadcrumb -->
	<ol class="breadcrumb pull-right">
		<li><a href="{{ route('home') }}">Home</a></li>
		<li class="active">Add Club</li>
	</ol>
	<!-- end breadcrumb -->
	<!-- begin page-header -->
	<h1 class="page-header">Club</h1>
	<!-- end page-header -->
	
	<!-- begin row -->
	<div class="row">
        <!-- begin col-6 -->
	    <div class="col-md-12">
	        <!-- begin panel -->
            <div class="panel panel-inverse" data-sortable-id="form-stuff-1">
                <div class="panel-heading">
                    <h4 class="panel-title">Add Club</h4>
                </div>
                <div class="panel-body">
                    <form class="form-horizontal" method="post" action="{{ route('club.store') }}" enctype="multipart/form-data">
                        @csrf

                        <div class="form-group">
                            <label class="col-md-3 control-label">Name</label>
                            <div class="col-md-6">
                                <input type="text" class="form-control" name="name" placeholder="Enter Club Name" required/>
                            </div>
                        </div>

                        <div class="form-group">
                            <div class="col-md-9 col-md-offset-3">
                                <button type="submit" class="btn btn-sm btn-success">Submit</button>
                            </div>
                        </div>
                    </form>
                </div>
            </div>
            <!-- end panel -->
        </div>
        <!-- end col-6 -->
    </div>
    <!-- end row -->
</div>
@endsection

resources/views/club/club_list.blade.php
@extends('layouts.admin')
@section('title','Club List')
@section('content')
<div id="content" class="content">
    <!-- begin breadcrumb -->
    <ol class="breadcrumb pull-right">
        <li><a href="{{ route('home') }}">Home</a></li>
        <li class="active">Club List</li>
    </ol>
    <!-- end breadcrumb -->
    <!-- begin page-header -->
    <h1 class="page-header">Club List</h1>
    <!-- end page-header -->
    <!-- begin row -->
    <div class="row">
        <!-- begin col-10 -->
        <div class="col-md-12">
            <!-- begin panel -->
            <div class="panel panel-inverse">
                <div class="panel-heading">
                    <h4 class="panel-title">Club List</h4>
                </div>
                
                <div class="panel-body">
                    <table id="data-table" class="table table-striped table-bordered nowrap" width="100%">
                        <thead>
                            <tr>
                                <th>Sr.no</th>
                                <th>Name</th>
                                <th>Action</th>
                            </tr>
                        </thead>
                        <tbody>
                        @if(count($clubList) > 0)
                            @foreach($clubList as $ck => $cv)   
                                <tr class="odd gradeX">
                                    <td>{{ $loop->iteration }}</td>
                                    <td>{{ $cv->name}}</td>
                                    <td>
                                        <a href="{{ route('club.edit',$cv->id) }}" class="btn btn-info btn-icon btn-circle btn-lg" style="float: left;"><i class="fa fa-edit" ></i></a>
                                        <form  method="post" action="{{ route('club.destroy',$cv->id) }}">
                                            @csrf
                                            @method('delete')
                                            <button type="submit" class="btn btn-danger btn-icon btn-circle btn-lg" onclick="return confirm('Are you sure want to delete this club ?')"><i class="fa fa-times"></i>
                                            </button>
                                        </form>
                                    </td>
                                </tr>
                            @endforeach
                        @endif
                        </tbody>
                    </table>
                </div>
            </div>
            <!-- end panel -->
        </div>
        <!-- end col-10 -->
    </div>
    <!-- end row -->
</div>
@endsection

resources/views/club/edit_club.blade.php
@extends('layouts.admin')
@section('title','Edit Club')
@section('content')
<div id="content" class="content">
	<!-- begin breadcrumb -->
	<ol class="breadcrumb pull-right">
		<li><a href="{{ route('home') }}">Home</a></li>
		<li class="active">Edit Club</li>
	</ol>
	<!-- end breadcrumb -->
	<!-- begin page-header -->
	<h1 class="page-header">Club</h1>
	<!-- end page-header -->
	
	<!-- begin row -->
	<div class="row">
        <!-- begin col-6 -->
	    <div class="col-md-12">
	        <!-- begin panel -->
            <div class="panel panel-inverse" data-sortable-id="form-stuff-1">
                <div class="panel-heading">
                    <h4 class="panel-title">Edit Club</h4>
                </div>
                <div class="panel-body">
                    <form class="form-horizontal" method="post" action="{{ route('club.update',$getClubInfo->id) }}" enctype="multipart/form-data">
                        @csrf
                        @method('put')

                        <input type="hidden" name="id" value="{{ $getClubInfo->id }}">

                        <div class="form-group">
                            <label class="col-md-3 control-label">Name</label>
                            <div class="col-md-6">
                                <input type="text" class="form-control" name="name" placeholder="Enter Name" value="{{ $getClubInfo->name }}" required/>
                            </div>
                        </div>

                        <div class="form-group">
                            <div class="col-md-9 col-md-offset-3">
                                <button type="submit" class="btn btn-sm btn-success">Submit</button>
                            </div>
                        </div>
                    </form>
                </div>
            </div>
            <!-- end panel -->
        </div>
        <!-- end col-6 -->
    </div>
    <!-- end row -->
</div>
@endsection